/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memclicker;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author pp2
 */
public class ClickerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClickerFrame
     */
    MemeOutputThread outThread;
    //array, witch contains count of threads for each function
    private int[] threadsArray = new int[7];
    //array, which contains count for mem per click buttons (perk buttons)
    private int[] clickArray = new int[5];
    MemeCounter memeCounter;
    
    //Frame constructor
    public ClickerFrame() {
        initComponents();
        memeCounter = new MemeCounter();
        
        Timer t = new Timer();
        t.scheduleAtFixedRate(timerTask, 0, 1000);
        //threadsArray init
        for (int i=0;i<7;i++) threadsArray[i]=0;
        //clickArray init
        for (int i=0;i<5;i++) clickArray[i]=0;
        outThread = new MemeOutputThread(memeCounter, jLabel1, jLabelMPS, threadsArray, jLabelRank, jLabelMPC);
        outThread.start();
        outThread.setFrame(this);
    }
     
    //Timer task for timer
    private TimerTask timerTask = new TimerTask(){
		private volatile int time = -1;
		
		private Runnable refresher = new Runnable()
		{
			@Override
			public void run ()
			{
				int t = time;
				jLabelTimer.setText(String.format("%02d:%02d", t / 60, t % 60));
			}
		};
		
		@Override
		public void run ()
		{
			time++;
			SwingUtilities.invokeLater(refresher);
		}
        };
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonFn1 = new javax.swing.JButton();
        jLabelFn1 = new javax.swing.JLabel();
        jButtonFn2 = new javax.swing.JButton();
        jLabelFn2 = new javax.swing.JLabel();
        jButtonFn3 = new javax.swing.JButton();
        jLabelFn3 = new javax.swing.JLabel();
        jButtonFn4 = new javax.swing.JButton();
        jLabelFn4 = new javax.swing.JLabel();
        jButtonFn5 = new javax.swing.JButton();
        jLabelFn5 = new javax.swing.JLabel();
        jButtonFn6 = new javax.swing.JButton();
        jLabelFn6 = new javax.swing.JLabel();
        jButtonFn7 = new javax.swing.JButton();
        jLabelFn7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCreateMeme = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTimer = new javax.swing.JLabel();
        jLabelMPS = new javax.swing.JLabel();
        jLabelMPC = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelRank = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonPr1 = new javax.swing.JButton();
        jLabelPr1 = new javax.swing.JLabel();
        jButtonPr2 = new javax.swing.JButton();
        jButtonPr3 = new javax.swing.JButton();
        jButtonPr4 = new javax.swing.JButton();
        jButtonPr5 = new javax.swing.JButton();
        jLabelPr2 = new javax.swing.JLabel();
        jLabelPr3 = new javax.swing.JLabel();
        jLabelPr4 = new javax.swing.JLabel();
        jLabelPr5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memes Clicker");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonFn1.setText("Позвать друга создавать мемесы 40/+1");
        jButtonFn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn1ActionPerformed(evt);
            }
        });

        jLabelFn1.setText("0");

        jButtonFn2.setText("Нанять чувака, который тырит мэмы с одноклассников 360/+4");
        jButtonFn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn2ActionPerformed(evt);
            }
        });

        jLabelFn2.setText("0");

        jButtonFn3.setText("Нанять битарда 960/+6");
        jButtonFn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn3ActionPerformed(evt);
            }
        });

        jLabelFn3.setText("0");

        jButtonFn4.setText("Открыть группу в ВК 3200/+10 ");
        jButtonFn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn4ActionPerformed(evt);
            }
        });

        jLabelFn4.setText("0");

        jButtonFn5.setText("Создать канал в телеграмме 12800/+14");
        jButtonFn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn5ActionPerformed(evt);
            }
        });

        jLabelFn5.setText("0");

        jButtonFn6.setText("Создать имиджборду 51200/+16");
        jButtonFn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn6ActionPerformed(evt);
            }
        });

        jLabelFn6.setText("0");

        jButtonFn7.setText("Открыть ютуб-канал 100000/+20");
        jButtonFn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFn7ActionPerformed(evt);
            }
        });

        jLabelFn7.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn1)
                    .addComponent(jLabelFn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn2)
                    .addComponent(jLabelFn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn3)
                    .addComponent(jLabelFn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn4)
                    .addComponent(jLabelFn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn5)
                    .addComponent(jLabelFn5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn6)
                    .addComponent(jLabelFn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFn7)
                    .addComponent(jLabelFn7))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Текущее количество мемесов");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");

        jButtonCreateMeme.setText("Создать мемес");
        jButtonCreateMeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateMemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCreateMeme, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCreateMeme, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Статистика");

        jLabel4.setText("Мемесов за клик");

        jLabel5.setText("Мемесов в секунду");

        jLabelTimer.setText("Таймер");

        jLabelMPS.setText("0");

        jLabelMPC.setText("0");

        jLabel6.setText("Текущий ранг");

        jLabelRank.setText("Current rank");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRank)
                    .addComponent(jLabelTimer)
                    .addComponent(jLabelMPS)
                    .addComponent(jLabelMPC))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMPC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelMPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelRank))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPr1.setText("Прокачать троллинг 500/+1");
        jButtonPr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPr1ActionPerformed(evt);
            }
        });

        jLabelPr1.setText("0");

        jButtonPr2.setText("Прокачать скилл в паинте 1000/+2");
        jButtonPr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPr2ActionPerformed(evt);
            }
        });

        jButtonPr3.setText("Скачать смешную картинку 1500/+3");
        jButtonPr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPr3ActionPerformed(evt);
            }
        });

        jButtonPr4.setText("Повысить свой мэдскиллз 2000/+4");
        jButtonPr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPr4ActionPerformed(evt);
            }
        });

        jButtonPr5.setText("Повысить научную степень в кекмемологии 2500/+5");
        jButtonPr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPr5ActionPerformed(evt);
            }
        });

        jLabelPr2.setText("0");

        jLabelPr3.setText("0");

        jLabelPr4.setText("0");

        jLabelPr5.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonPr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPr1)
                    .addComponent(jLabelPr2)
                    .addComponent(jLabelPr3)
                    .addComponent(jLabelPr4)
                    .addComponent(jLabelPr5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPr1)
                    .addComponent(jLabelPr1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPr2)
                    .addComponent(jLabelPr2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPr3)
                    .addComponent(jLabelPr3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPr4)
                    .addComponent(jLabelPr4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPr5)
                    .addComponent(jLabelPr5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateMemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateMemeActionPerformed
        memeCounter.increaseCounter(memeCounter.getMPC());
    }//GEN-LAST:event_jButtonCreateMemeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        outThread.stopThread();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonFn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn1ActionPerformed
        addFunctionThread(40,1,0);
        jLabelFn1.setText(Integer.toString(threadsArray[0]));
        
    }//GEN-LAST:event_jButtonFn1ActionPerformed

    private void jButtonFn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn2ActionPerformed
        addFunctionThread(360,4,1);
        jLabelFn2.setText(Integer.toString(threadsArray[1]));
    }//GEN-LAST:event_jButtonFn2ActionPerformed

    private void jButtonFn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn3ActionPerformed
        addFunctionThread(960,6,2);
        jLabelFn3.setText(Integer.toString(threadsArray[2]));
    }//GEN-LAST:event_jButtonFn3ActionPerformed

    private void jButtonFn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn4ActionPerformed
        addFunctionThread(3200,10,3);
        jLabelFn4.setText(Integer.toString(threadsArray[3]));
    }//GEN-LAST:event_jButtonFn4ActionPerformed

    private void jButtonFn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn5ActionPerformed
        addFunctionThread(12800,14,4);
        jLabelFn5.setText(Integer.toString(threadsArray[4]));
    }//GEN-LAST:event_jButtonFn5ActionPerformed

    private void jButtonFn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn6ActionPerformed
        addFunctionThread(51200,16,5);
        jLabelFn6.setText(Integer.toString(threadsArray[5]));
    }//GEN-LAST:event_jButtonFn6ActionPerformed

    private void jButtonFn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFn7ActionPerformed
        addFunctionThread(100000,20,6);
        jLabelFn7.setText(Integer.toString(threadsArray[6]));
    }//GEN-LAST:event_jButtonFn7ActionPerformed

    private void jButtonPr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPr1ActionPerformed
        addOnclickMemeAmount(1,0,500);
        jLabelPr1.setText(Integer.toString(clickArray[0]));
    }//GEN-LAST:event_jButtonPr1ActionPerformed

    private void jButtonPr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPr2ActionPerformed
        addOnclickMemeAmount(2,1,1000);
        jLabelPr2.setText(Integer.toString(clickArray[1]));
    }//GEN-LAST:event_jButtonPr2ActionPerformed

    private void jButtonPr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPr3ActionPerformed
        addOnclickMemeAmount(3,2,1500);
        jLabelPr3.setText(Integer.toString(clickArray[2]));
    }//GEN-LAST:event_jButtonPr3ActionPerformed

    private void jButtonPr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPr4ActionPerformed
       addOnclickMemeAmount(4,3,2000);
        jLabelPr4.setText(Integer.toString(clickArray[3]));
    }//GEN-LAST:event_jButtonPr4ActionPerformed

    private void jButtonPr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPr5ActionPerformed
        addOnclickMemeAmount(5,4,2500);
        jLabelPr5.setText(Integer.toString(clickArray[4]));
    }//GEN-LAST:event_jButtonPr5ActionPerformed
  
    /**
     * Optimizing a little bit. Starting a new thread that adding some memes to total counter.
     * @param value - memes needed to buy function
     * @param addValue - amount of memes added by function
     * @param arrayFNum - number of function in array
     */
    private void addFunctionThread(int value, int addValue, int arrayFNum){
        if (memeCounter.getCounter()>=value){
            memeCounter.decreaseCounter(value);
        AdderThread add = new AdderThread(memeCounter, addValue);
        add.start();
        threadsArray[arrayFNum]++;
        }
    }
    
    /**
     * Adding onclick amount for main button.
     * @param mpcAddAmount amount on which MPC will increase
     * @param arrayCNum number of perk in array
     * @param price price of addition
     */
    private void addOnclickMemeAmount(int mpcAddAmount, int arrayCNum, long price){
        if (memeCounter.getCounter()>=price){
            memeCounter.increaseMPC(mpcAddAmount);
            clickArray[arrayCNum]++;
            memeCounter.decreaseCounter(price);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClickerFrame().setVisible(true);
            }
        });
    }

    public void showWinMessage(){
        JOptionPane.showMessageDialog(this,"Ты выиграл короч! Люто бешенно!", "ЛЮТЫЙ ВИН!!1", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateMeme;
    private javax.swing.JButton jButtonFn1;
    private javax.swing.JButton jButtonFn2;
    private javax.swing.JButton jButtonFn3;
    private javax.swing.JButton jButtonFn4;
    private javax.swing.JButton jButtonFn5;
    private javax.swing.JButton jButtonFn6;
    private javax.swing.JButton jButtonFn7;
    private javax.swing.JButton jButtonPr1;
    private javax.swing.JButton jButtonPr2;
    private javax.swing.JButton jButtonPr3;
    private javax.swing.JButton jButtonPr4;
    private javax.swing.JButton jButtonPr5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFn1;
    private javax.swing.JLabel jLabelFn2;
    private javax.swing.JLabel jLabelFn3;
    private javax.swing.JLabel jLabelFn4;
    private javax.swing.JLabel jLabelFn5;
    private javax.swing.JLabel jLabelFn6;
    private javax.swing.JLabel jLabelFn7;
    private javax.swing.JLabel jLabelMPC;
    private javax.swing.JLabel jLabelMPS;
    private javax.swing.JLabel jLabelPr1;
    private javax.swing.JLabel jLabelPr2;
    private javax.swing.JLabel jLabelPr3;
    private javax.swing.JLabel jLabelPr4;
    private javax.swing.JLabel jLabelPr5;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
